# Generated by Django 5.0.7 on 2024-08-06 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 8, 6, 19, 41, 4, 472791, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
