# Generated by Django 5.0.7 on 2024-08-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0003_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
